export const PFM_HEADERS = [
  "SR  NO",
  "Project Name",
  "Enter Module",
  "Enter Module Name",
  "Unit",
  "Part Snap",
  "Engg Part Number",
  "Synthetic Part No.",
  "Part Scope",
  "Part Description",
  "QPS (nos)",
  "Part Category",
  "FG SAP P/N (Taken from DP-PBOM-DA RAFALE FUSELAGE-Lateral Shells_REV03)",
  "EQN",
  "RM RAS Code",
  "SAP RM MM Code",
  "RM material Type",
  "RM Input Type",
  "Alloy",
  "Material Spec Mentioned",
  "Initial Temper",
  "Final Temper",
  "RM Sheet Length (mm)",
  "RM Sheet Width (mm)",
  "Sheet Thk (mm)",
  "Material with Concatenate",
  "Heat Treatment Applicability",
  "RM Remark",
  "Functional Class  (As per COS model Properties)",
  "Class Description  (As per DGQT 0.2.0.0001A)",
  "Mfg Code ST10804   (As per COS model Properties)",
  "Mfg Code Description as per ST10804 sec-2.1",
  "Process Code   (As per COS model Properties)",
  "Process code Description as per  ST10805  (Reference from ST10804 sec-2)",
  "Finish part Length (mm)",
  "Finish part width (mm)",
  "Part  Complexity",
  "Total No. of holes",
  "Special features",
  "Part Family's",
  "Major Fabrication Technology",
  "Base Matrix Applicability",
  "Nos of Bends",
  "Nos of Bends Score",
  "Type of Part (Flat , Formed)",
  "Type of Part Score",
  "Type of Forming (Hot forming, Cold Forming)",
  "Type of Forming Score",
  "Forming Temper condition (F,H11,O,T,T42,AQ/W)",
  "Forming Temper condition Score",
  "Type of Bend (Concave, convex, straight)",
  "Type of Bend Score",
  "Joggle (Joggle Depth , Nos of Joggle , Joggle ratio)",
  "Joggle Score",
  "Thickness Mill (Chemical Mill , Mechanical Mill , Nos of Pockets)",
  "Thickness Mill Score",
  "Type of Raw material",
  "Type of Raw material Score",
  "Part Thickness (min, mm)",
  "Part Thickness Score",
  "GD&T — Hole Position",
  "GD&T Hole Position Score",
  "GD&T — Form & Profile Controls",
  "GD&T Form & Profile Controls Score",
  "Base Matrix Total Score",
  "Protection Code",
  "Special process Sequence",
  "Conductivity Test",
  "Chemical Milling",
  "Welding",
  "Desensitization",
  "Pre-penetrant etch",
  "Non Destructive testing",
  "Sand-blasting",
  "Pickling",
  "TSA",
  "CAA",
  "Manual CCC (For Electrical bonding area)",
  "Primer",
  "Topcoat",
  "Plastic Coating",
  "No Protection",
  "Remarks",
  "Part Marking Code",
  "Mfg Process ME",
  "TRB Number & Date",
  "TRB Decision",
  "Final TRB Discussion Base on tool commonization Date: 20-02-2026",
  "TRB Remark",
  "Tooling Remarks",
  "Remark",
  "Nos of Tools Mfg",
  "Nos of Tools Std",
  "Cutting tools",
  "SM-ME Remarks"
];
