export const PFM_HEADERS = [
  "SR  NO",
  "Part Snap",
  "Engg Part Number",
  "Synthetic Part No.",
  "Part Scope",
  "Part Description",
  "QPS (nos)",
  "Part Category",
  "FG SAP P/N (Taken from DP-PBOM-DA RAFALE FUSELAGE-Lateral Shells_REV03)",
  "EQN",
  "RM RAS Code",
  "SAP RM MM Code",
  "RM material Type",
  "RM Input Type",
  "Material Spec Mentioned",
  "Alloy",
  "Initial Temper",
  "Final Temper",
  "RM Sheet Length (mm)",
  "RM Sheet Width (mm)",
  "Sheet Thk (mm)",
  "Material with Concatenate",
  "Heat Treatment Applicability",
  "RM Remark",
  "Functional Class  (As per COS model Properties)",
  "Class Description  (As per DGQT 0.2.0.0001A)",
  "Mfg Code ST10804   (As per COS model Properties)",
  "Mfg Code Description as per ST10804 sec-2.1",
  "Process Code   (As per COS model Properties)",
  "Process code Description as per  ST10805  (Reference from ST10804 sec-2)",
  "Finish part Length (mm)",
  "Finish part width (mm)",
  "Part  Complexity",
  "Hole engg Requirement (As per COS)",
  "Chamfer",
  "Part Family's",
  "Major Fabrication Technology",
  "Mfg Process ME",
  "TRB Number & Date",
  "TRB Decision",
  "Final TRB Discussion Base on tool commonization Date: 20-02-2026",
  "TRB Remark",
  "Tooling Remarks",
  "Part Marking Code",
  "Remark",
  "Nos of Tools Mfg",
  "Nos of Tools Std",
  "Cutting tools",
  "SM-ME Remarks",
  "Protection Code",
  "Special process Sequence",
  "Conductivity Test",
  "Chemical Milling",
  "Welding",
  "Desensitization",
  "Pre-penetrant etch",
  "Non Destructive testing",
  "Sand-blasting",
  "Pickling",
  "TSA",
  "CAA",
  "Manual CCC (For Electrical bonding area)",
  "Primer",
  "Topcoat",
  "Plastic Coating",
  "No Protection",
  "Remarks"
];
