export const DROPDOWN_OPTIONS: Record<string, string[]> = {
    // YES/NO options
    "Unit": ["Inch", "MM"],
    "Enter Module": ["Yes", "No"],
    "Heat Treatment Applicability": ["Yes", "No"],
    "Special features": ["Chamfer", "Fillet", "Csk", "Counter bore", "Drain hole"],
    "Conductivity Test": ["Yes", "No"],
    "Chemical Milling": ["Yes", "No"],
    "Welding": ["Yes", "No"],
    "Desensitization ": ["Yes", "No"],
    "Pre-penetrant etch": ["Yes", "No"],
    "Non Destructive testing": ["Yes", "No"],
    "Sand-blasting": ["Yes", "No"],
    "Pickling": ["Yes", "No"],
    "TSA": ["Yes", "No"],
    "CAA": ["Yes", "No"],
    "Manual CCC (For Electrical bonding area)": ["Yes", "No"],
    "Primer": ["Yes", "No"],
    "Topcoat": ["Yes", "No"],
    "Plastic Coating": ["Yes", "No"],
    "No Protection": ["Yes", "No"],
    "Functional Class Applicability": ["Yes", "No"],
    "Mfg Code Applicability": ["Yes", "No"],
    "Process Code Applicability": ["Yes", "No"],
    "EQN": ["Yes", "No"],
    "Base Matrix Applicability": ["Yes", "No"],

    // From PPT
    "Total No. of holes": [
        "Finish Holes",
        "Pilot/Pre-drilled Holes",
        "Coordination/Tooling Holes"
    ],
    "Part Category": ["SKN - Skin", "FRM - Frame", "RIB - Rib", "SPR - Spar", "STR - Stringer", "BRK - Bracket", "FIT - Fitting", "FAR - Fairings", "BEM - Beam", "DOR - Door", "SUP - Support", "WPL - Wing Panels", "SHM - Shims", "ANG - Angles", "INC - Intercostals", "CLP - Clip", "DOU - Doubler", "Detail Part", "Assembly", "Sub-Assembly"],
    "RM material Type": ["Inconel", "Aluminium", "Titanium", "Steel", "Copper"],
    "RM Input Type": ["SHT - Sheet", "EX - Extrusion", "TB - Tube", "Sheet", "Plate", "Casting", "Forging"],
    "Part Scope": ["TASL-N01", "TASL-H01", "TASL-N02", "Buy Scope"],
    "Initial Temper": ["F", "O", "H111", "T3", "T4", "Any other"],
    "Final Temper": ["T3", "T42", "T4", "T72", "T62", "T3511", "T351", "If any"],
    "Nos of Bends": ["0", "1-2 (C type)", "1-2 (Z Type)", "3-5", ">5"],
    "Family Name": [
        "SKN - Skin", "FRM - Frame", "RIB - Rib", "SPR - Spar", "STR - Stringer",
        "BRK - Bracket", "FIT - Fitting", "FAR - Fairings", "BEM - Beam",
        "DOR - Door", "SUP - Support", "WPL - Wing Panels", "SHM - Shims",
        "ANG - Angles", "INC - Intercostals", "CLP - Clip", "DOU - Doubler",
        "Any Other"
    ],
    "Type of Part (Flat , Formed)": ["Flat ( Up 1M)", "Flat ( < 1M)", "Formed (Up to 0.5M)", "Formed (0.5 M to 1.5M)", "Formed (< 1.5 M)"],
    "Type of Forming (Hot forming, Cold Forming)": ["Cold Forming ( Up 1M)", "Cold Forming (1M - 2.0M)", "Hot Joggle", "Hot Forming (Up to 0.5M)", "Hot Forming (< 0.5M)", "Hyd Press"],
    "Forming Temper condition (F,H11,O,T,T42,AQ/W)": ["O / H111 / F / No Forming (Any Alloy)", "TX", "AQ / W", "TXXXX", "Non Aluminium Temper"],
    "Type of Bend (Concave, convex, straight)": ["Straight", "Single Emboss/Bead", "Convex / Multiple Emboss / Bead / Shallow Forming > 10mm", "Concave / Multiple Emboss / Bead / Shallow Forming 10 - 20mm", "Multi Curvature / Deep Draw (< 30 mm)"],
    "Joggle (Joggle Depth , Nos of Joggle , Joggle ratio)": ["Single Joggle / Joggle Depth *** / Joggle Ratio **", "Joggle Nos 1-2 / Joggle Depth *** / Joggle Ratio **", "Joggle Nos 2 -3 / Joggle Depth *** / Joggle Ratio ***", "Joggle Nos 3 - 4 / Joggle Depth *** / Joggle Ratio **", "Joggle Nos <4 / Joggle Depth *** / Joggle Ratio **"],
    "Thickness Mill (Chemical Mill , Mechanical Mill , Nos of Pockets)": ["No thickness Mill", "Mechanical Mill or Chemical Mill (1 Stage , 1 Pocket)", "Mechanical Mill or Chemical Mill (1-2 Stage , 1-2 Pocket)", "Mechanical Mill or Chemical Mill (2-3 Stage , 2-3 Pocket)", "Mechanical Mill or Chemical Mill (More than 3 Stage , More than 3 Pocket)"],
    "Type of Raw material": ["Aluminum Shims", "Aluminum Extrusion , Sheet", "Ti Sheet", "Steel Sheet", "Inconal Sheet"],
    "Part Thickness (min, mm)": ["Up to 0.4 mm", "0.4 - 1.0 mm", "1.0 mm to 1.5 mm", "1.6 mm to 4.0 mm", "> 4.0 mm"],
    "GD&T — Hole Position": ["No GD&T", "Single Datum / tolerance Limit > 0.8mm / No Hole MMC/LLC", "Multiple Datum / Tolerance Limit : 0.6-0.8 mm / No Hole MMC/LLC", "Multiple Datum / Tolerance Limit : 0.6-0.8 mm / Hole with MMC/LLC", "Multiple Datum / Tolerance Limit < 0.6 mm / Hole with MMC/LLC"],
    "GD&T — Form & Profile Controls": ["No GD&T", "Flatness > 1mm / Profile >1mm / Straight Profile", "Flatness 0.8–1mm / Profile 0.8–1mm / Straight Profile", "Flatness 0.8–1mm / Profile 0.8–1mm / Straight Profile", "Flatness <0.8mm / Profile <0.8 / Free-form contour"],
    "Part Marking Code": [
        "Ink marking",
        "Level / Bagend tag",
        "MBos Marking",
        "Engraved Marking",
        "If Any"
    ]
};
